import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, BookOpen, Workflow, MessagesSquare, ChartNoAxesCombined } from 'lucide-react';
import { CorporateHeader } from '@/components/CorporateHeader';
import { CorporateNewsletter } from '@/components/CorporateNewsletter';
import { CorporateFooter } from '@/components/CorporateFooter';
import styles from './business.module.css';
import { diagnosticUrl } from '@/lib/site-links';

const solutions = [
  { icon: Workflow, title: 'Automatización de procesos', text: 'Conecta tareas y herramientas para que la información avance sin depender de copiar, pegar y perseguir pendientes.', tags: ['Operaciones', 'Flujos de trabajo'] },
  { icon: MessagesSquare, title: 'Asistentes para tu equipo', text: 'Facilita el acceso al conocimiento interno y apoya las respuestas a clientes con contexto y revisión humana.', tags: ['Conocimiento', 'Servicio al cliente'] },
  { icon: ChartNoAxesCombined, title: 'Información para decidir', text: 'Organiza documentos, analiza información y prepara reportes que ayuden a tu equipo a tomar decisiones.', tags: ['Análisis', 'Documentación'] },
  { icon: BookOpen, title: 'Formación y adopción', text: 'Integra la IA en el trabajo cotidiano con sesiones prácticas, criterios de uso y casos propios de tu empresa.', tags: ['Equipos', 'Capacitación'] },
];

export default function Home() {
  return <div className={styles.site}><CorporateHeader/><main id="contenido">
    <section className={styles.hero} aria-labelledby="presentacion"><div className={styles.heroInner}><div>
      <p className={styles.eyebrow}>ESTRATEGIA · AUTOMATIZACIÓN · IA PARA EMPRESAS</p><h1 id="presentacion">Andrés Gómez<span>.</span></h1>
      <p className={styles.statement}>Convierto la inteligencia artificial en una herramienta de trabajo para tu empresa.</p><p className={styles.description}>Procesos más claros, menos tareas repetitivas y equipos que saben cómo usar la IA. Empezamos por una necesidad real de tu negocio y construimos desde ahí.</p>
      <dl className={styles.facts}><div><dt>ENFOQUE</dt><dd>IA aplicada a negocios</dd></div><div><dt>PROCESO</dt><dd>Del diagnóstico al piloto</dd></div><div><dt>PRIORIDAD</dt><dd>Tu equipo y su operación</dd></div></dl>
      <div className={styles.heroDiagnostic}><span>DIAGNÓSTICO DE IA PARA EMPRESAS</span><a className={styles.primary} href={diagnosticUrl}>Evalúa tu empresa en 5 minutos <ArrowUpRight size={20}/></a><p>Un primer paso para identificar dónde aplicar IA en tu negocio.</p></div>
      <div className={styles.actions}><a className={styles.secondary} href="#contacto">Hablemos de tu empresa <ArrowRight size={18}/></a><Link className={styles.secondary} href="/recursos">Explorar recursos <ArrowUpRight size={18}/></Link></div><a className={styles.email} href="mailto:hello@andresgomez.store">HELLO@ANDRESGOMEZ.STORE <ArrowUpRight size={14}/></a>
    </div><figure className={styles.portrait}><div className={styles.portraitImage}><Image src="/profie-traje-negro.webp" alt="Andrés Gómez" fill sizes="(max-width: 800px) 90vw, 430px" priority unoptimized/></div><figcaption><span>ANDRÉS GÓMEZ · @ANDRESGOMEZ.IA</span><strong><i/> IA CON CRITERIO DE NEGOCIO</strong></figcaption></figure></div></section>
    <div className={styles.disciplines}><span>EL TRABAJO, CON MENOS FRICCIÓN</span><ul><li>Automatización</li><li>Asistentes de IA</li><li>Datos y documentos</li><li>Formación de equipos</li></ul></div>
    <section id="soluciones" className={styles.section} aria-labelledby="soluciones-titulo"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>01 / SOLUCIONES</p><h2 id="soluciones-titulo">IA para el trabajo real.</h2></div><p>No todas las tareas necesitan IA. Identificamos dónde puede ser útil y cómo integrarla en tu operación.</p></div><div className={styles.solutions}>{solutions.map(({icon: Icon,title,text,tags},index)=><article className={styles.solution} key={title}><div className={styles.solutionTop}><Icon size={25} strokeWidth={1.5}/><span>0{index+1}</span></div><h3>{title}</h3><p>{text}</p><div className={styles.tags}>{tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>)}</div></section>
    <section id="enfoque" className={`${styles.section} ${styles.approach}`} aria-labelledby="enfoque-titulo"><div><p className={styles.eyebrow}>02 / FORMA DE TRABAJAR</p><h2 id="enfoque-titulo">Primero el proceso.<br/>Después, la tecnología.</h2><p className={styles.description}>La implementación empieza por entender cómo trabaja tu equipo. Un piloto permite comprobar la utilidad antes de extender la solución.</p></div><ol className={styles.steps}><li><span>01</span><div><h3>Entender la necesidad</h3><p>Revisamos tareas, herramientas y puntos de fricción. Elegimos un caso de uso concreto.</p></div></li><li><span>02</span><div><h3>Construir y validar</h3><p>Probamos un piloto con objetivos claros, permisos definidos y revisión humana.</p></div></li><li><span>03</span><div><h3>Acompañar la adopción</h3><p>Documentamos el flujo y formamos al equipo para que pueda usarlo y mejorarlo.</p></div></li></ol></section>
    <section className={styles.section} aria-labelledby="recursos-titulo"><div className={styles.sectionHeading}><div><p className={styles.eyebrow}>03 / CONOCIMIENTO ABIERTO</p><h2 id="recursos-titulo">Aprender también es avanzar.</h2></div><p>Guías, prompts y plantillas para explorar la IA y llevar lo aprendido a tu trabajo.</p></div><Link href="/recursos" className={styles.resourceLink}><div><span>BIBLIOTECA DE RECURSOS</span><h3>Una base práctica para usar mejor la IA.</h3><p>Prompts · Automatización · Contenido · Creación visual</p></div><span className={styles.resourceArrow}><ArrowUpRight size={32}/></span></Link></section>
    <section id="diagnostico" className={`${styles.section} ${styles.diagnostic}`} aria-labelledby="diagnostico-titulo"><div><p className={styles.eyebrow}>04 / DIAGNÓSTICO</p><h2 id="diagnostico-titulo">El primer paso para aplicar IA<br/> en tu empresa.</h2><p className={styles.description}>Revisa dónde está tu negocio hoy y qué procesos podrían beneficiarse de la inteligencia artificial. Empieza por entender tus necesidades y prioridades.</p></div><div className={styles.diagnosticAction}><span>DE LA IDEA A UN PUNTO DE PARTIDA</span><a className={styles.primary} href={diagnosticUrl}>Iniciar diagnóstico <ArrowUpRight size={20}/></a><p>Explora las oportunidades de IA para tu negocio.</p></div></section>
    <section id="contacto" className={styles.contact} aria-labelledby="contacto-titulo"><div className={styles.contactInner}><div className={styles.contactCopy}><p className={styles.eyebrow}>CONTACTO</p><h2 id="contacto-titulo">Si un proceso se come las horas de tu equipo, hablemos.</h2><p>Cuéntame qué quieres mejorar, qué herramientas utilizas y qué resultado esperas. Empecemos por una necesidad real de tu empresa.</p></div><div className={styles.contactActions}><a className={styles.primary} href="mailto:hello@andresgomez.store?subject=IA%20para%20mi%20empresa">Trabaja conmigo <ArrowRight size={21}/></a><a className={styles.email} href="mailto:hello@andresgomez.store">HELLO@ANDRESGOMEZ.STORE</a><a className={styles.eventLink} href="mailto:hello@andresgomez.store?subject=Invitaci%C3%B3n%20a%20un%20evento">INVÍTAME A TU EVENTO <ArrowRight size={16}/></a></div></div></section>
    <div className={styles.newsletterSection}><CorporateNewsletter/></div>
  </main><CorporateFooter/></div>;
}
